config/routes.rb
# frozen_string_literal: true

# == Route Map
#            Prefix Verb                 URI Pattern                            Controller#Action
#                new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#                    user_session POST   /users/sign_in(.:format)               devise/sessions#create
#            destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#               new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#              edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                   user_password PATCH  /users/password(.:format)              devise/passwords#update
#                                 PUT    /users/password(.:format)              devise/passwords#update
#                                 POST   /users/password(.:format)              devise/passwords#create
#                            root GET    /                                      devise/sessions#new
#           admin_dashboard_index GET    /admin/dashboard(.:format)             admin/dashboard#index
#                   admin_clients GET    /admin/clients(.:format)               admin/clients#index
#                                 POST   /admin/clients(.:format)               admin/clients#create
#                new_admin_client GET    /admin/clients/new(.:format)           admin/clients#new
#               edit_admin_client GET    /admin/clients/:id/edit(.:format)      admin/clients#edit
#                    admin_client GET    /admin/clients/:id(.:format)           admin/clients#show
#                                 PATCH  /admin/clients/:id(.:format)           admin/clients#update
#                                 PUT    /admin/clients/:id(.:format)           admin/clients#update
#                                 DELETE /admin/clients/:id(.:format)           admin/clients#destroy
#                  admin_plumbers GET    /admin/plumbers(.:format)              admin/plumbers#index
#                                 POST   /admin/plumbers(.:format)              admin/plumbers#create
#               new_admin_plumber GET    /admin/plumbers/new(.:format)          admin/plumbers#new
#              edit_admin_plumber GET    /admin/plumbers/:id/edit(.:format)     admin/plumbers#edit
#                   admin_plumber GET    /admin/plumbers/:id(.:format)          admin/plumbers#show
#                                 PATCH  /admin/plumbers/:id(.:format)          admin/plumbers#update
#                                 PUT    /admin/plumbers/:id(.:format)          admin/plumbers#update
#                                 DELETE /admin/plumbers/:id(.:format)          admin/plumbers#destroy
#                      admin_jobs POST   /admin/jobs(.:format)                  admin/jobs#create
#                   new_admin_job GET    /admin/jobs/new(.:format)              admin/jobs#new
#                     api_v1_jobs GET    /api/v1/jobs(.:format)                 api/v1/jobs#index {:format=>"json"}
#                      api_v1_job PATCH  /api/v1/jobs/:id(.:format)             api/v1/jobs#update {:format=>"json"}
#                                 PUT    /api/v1/jobs/:id(.:format)             api/v1/jobs#update {:format=>"json"}
#                          api_v1        /api/v1/*path(.:format)                api/v1/api#routing_error {:format=>"json"}
# turbo_recede_historical_location GET    /recede_historical_location(.:format)  turbo/native/navigation#recede
# turbo_resume_historical_location GET    /resume_historical_location(.:format)  turbo/native/navigation#resume
# turbo_refresh_historical_location GET    /refresh_historical_location(.:format) turbo/native/navigation#refresh

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end

  namespace :admin do
    resources :dashboard, only: %i[index]
    resources :clients
    resources :plumbers
    resources :jobs, only: %i[new create]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :jobs, only: %i[index update]

      match '*path', to: 'api#routing_error', via: :all
    end
  end
end

app/models/client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  address                :string
#  age                    :integer
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           not null
#  private_note           :text
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string           default("Plumber"), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class Client < User

  # Validations
  validates :age, presence: true
  validates :private_note, presence: true
  validates :address, presence: true

  # Associations
  has_many :jobs
  has_many :plumbers, through: :jobs

  # Pending jobs
  def pending_jobs
    jobs.where(status: :pending)
  end

  private

  # Overridden method since clients are not required to login - out of assignment scope
  def password_required?
    return false
  end
end

app/controllers/admin/clients_controller.rb
# frozen_string_literal: true

module Admin
  class ClientsController < ApplicationController
    before_action :set_client, only: %i[show edit update destroy]

    def index
      @clients = Client.all
    end

    def show; end

    def new
      @client = Client.new
    end

    def edit; end

    def create
      @client = Client.new(client_params)

      if @client.save
        redirect_to admin_client_url(@client), notice: I18n.t('controllers.clients.create.success')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @client.update(client_params)
        redirect_to admin_client_url(@client), notice: I18n.t('controllers.clients.update.success')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @client.destroy

      redirect_to admin_clients_url, notice: I18n.t('controllers.clients.destroy.success')
    end

    private

    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :email, :age, :address, :private_note)
    end
  end
end

app/views/admin/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= client.age %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= client.address %>
  </p>

  <p>
    <strong>Private note:</strong>
    <%= client.private_note %>
  </p>
</div>

app/views/admin/clients/_form.html.erb
<%= form_for(client, url: admin_clients_path) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :private_note, style: "display: block" %>
    <%= form.text_field :private_note %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", admin_client_path(@client) %> |
  <%= link_to "Back to clients", admin_clients_path %>
  <%= link_to "Back to dashboard", admin_dashboard_index_path %>
</div>

app/views/admin/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to client.name, admin_client_path(client) %>
    </p>
  <% end %>
</div>

<br>

<%= link_to "New client", new_admin_client_path %>
<%= link_to "Back to dashboard", admin_dashboard_index_path %>

app/views/admin/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", admin_clients_path %>
  <%= link_to "Back to dashboard", admin_dashboard_index_path %>
</div>

app/views/admin/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>
<br>
<div>
  <%= link_to "Edit this client", edit_admin_client_path(@client) %>
  <%= link_to "Back to clients", admin_clients_path %>
  <br>
  <%= button_to "Destroy this client", admin_client_path(@client), method: :delete %>
  <%= link_to "Back to dashboard", admin_dashboard_index_path %>
</div>